services:
  client:
    profiles: [ client, all ]
    build: client/
    command: npm run dev
    volumes:
      - ./client/src:/app/src
    ports:
      - '5173:5173'

  spacetime:
    profiles: [ stdb, all ]
    image: clockworklabs/spacetime:v1.0.1
    user: root
    command: start
    environment:
      HOME: /home/spacetime
    volumes:
      - ./server:/app
      - ./client/src/lib/module_bindings:/client-app/src/lib/module_bindings
      - ./.docker/spacetime/data:/home/spacetime/.local/share/spacetime/data
    ports:
      - '3000:3000'
